travis:
  secure:
    BINSTAR_TOKEN: Cdy3VxzKIXBhutLo40K3ZDGqjWae7SKuitTOaI3j5LLLAOBM7f1l4o6DhgLLgJwOVmtxcQTX7Hst6tFLluxUbToIUUy3PT8NFiwbllsOOq6zZESjFCrzP9pFfc//asL2o9LaFErvFd4vQUZWUOdVN/W6mN9N/O3fs140IOcJYiKUrgHF6EI+hT5IlYNABl33slEWQmZCglkAadWdmc69hF2Mx4tCB+RhCor01PsGL7GQLFNvUg9HYSvMsZ+LetZRrslEK2jN0p/NjumejgJ+batCOQHw3JRCermEjLP++uHh+utznIgTPUUfUlNRVXdPYvcWDBTUsG6Hnmc/8BUmQCQMzRMGgtzlBfAvzbuGKeCC8Qc9v0nhy+OVIMFztAEXIePdE6ni/eB1tX57OfPEg4yc30vDIoKGfUwPOiemcfYU9WKRn6wvm7OEIFomB3UHOZZwVpK4zVbYsITnyF4Bqj3PtQgt1tWjAGwky2u1/tz8Qot6RXx8lhUeG0iMzzRlo2ENNpO1Qz5RigbIGixGK0z6d/zZwDHLKfTzG+wgynqpXjtDAhYnPX0tEb4tGu53Rg6N1axtcfHWGz6C4F37gRUbhxX/4t9zR+Aep9bphTRDud8cLScN3kNyH4nn0JUtL5Atl4i16ghg1nynJ8he/hx6AWw4kWjlv+ysy5V7Gu0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
